/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AmountInput: typeof import('./components/common/AmountInput.vue')['default']
    BarbellGauge: typeof import('./components/barbell/BarbellGauge.vue')['default']
    CryptoStakeBanner: typeof import('./components/summary/CryptoStakeBanner.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FearGreedMeter: typeof import('./components/summary/FearGreedMeter.vue')['default']
    FormulaTooltip: typeof import('./components/accounts/FormulaTooltip.vue')['default']
    FundProductPanel: typeof import('./components/accounts/FundProductPanel.vue')['default']
    FunFundPocket: typeof import('./components/salary/FunFundPocket.vue')['default']
    GlobalFxBar: typeof import('./components/fx/GlobalFxBar.vue')['default']
    HtxDailyYieldDialog: typeof import('./components/accounts/HtxDailyYieldDialog.vue')['default']
    LoanPanel: typeof import('./components/accounts/LoanPanel.vue')['default']
    NetWorthHero: typeof import('./components/summary/NetWorthHero.vue')['default']
    PaydayStatusBanner: typeof import('./components/salary/PaydayStatusBanner.vue')['default']
    PoolAccountCard: typeof import('./components/accounts/PoolAccountCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SafetyLineAlert: typeof import('./components/summary/SafetyLineAlert.vue')['default']
    SafetyPadStatus: typeof import('./components/salary/SafetyPadStatus.vue')['default']
    SalaryAllocationTable: typeof import('./components/salary/SalaryAllocationTable.vue')['default']
    SavingsRateBanner: typeof import('./components/summary/SavingsRateBanner.vue')['default']
    StockHoldingCard: typeof import('./components/accounts/StockHoldingCard.vue')['default']
    YuanGouPanel: typeof import('./components/accounts/YuanGouPanel.vue')['default']
  }
}
